spring:
#  security:
#    user:
#      name: user
#      password: 123
  activemq:
    user: artemis
    password: artemis
  datasource:
    url: jdbc:mysql://localhost:3306/attendance_sys?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:

    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true